version: '3.5'
networks:
  web:
    external: true
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      default:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=EXPRESS
      - SA_PASSWORD=z@123456!
    ports:
      - target: 1433
        published: 1434
  e-trans-vinhomes-api:
    container_name: e-trans-vinhomes-api
    tty: true
    depends_on:
      - rabbitmq
      - sql-server
    image: ${DOCKER_REGISTRY-}e-trans-vinhomes-api:v1
    build:
      context: .
      dockerfile: ETransVinhomesAPI/Dockerfile
    environment:
    - CONNECTIONSTRINGS__DEFAULT=Server=sql-server;Database=ETransVinhomes;Trusted_Connection=False;User Id=sa;Password=z@123456!;MultipleActiveResultSets=true;TrustServerCertificate=true
    ports:
    - "4201:80"
    healthcheck:
      test: curl --fail http://localhost:/4201 || exit 1
      interval: 1m30s
      timeout: 15s
      retries: 5
      start_period: 30s
  e-trans-vinhomes-auth-api:
    container_name: e-trans-vinhomes-auth-api
    tty: true
    image: ${DOCKER_REGISTRY-}e-trans-vinhomes-auth-api:v1
    depends_on:
      - rabbitmq
      - sql-server
    build: 
      context: .
      dockerfile: ETransVinhomes.AuthAPI/Dockerfile
    environment:
    - CONNECTIONSTRINGS__DEFAULT=Server=sql-server;Database=ETransVinhomes.Auth;Trusted_Connection=False;User Id=sa;Password=z@123456!;MultipleActiveResultSets=true;TrustServerCertificate=true
    ports:
    - "4202:80"


