version: '3.5'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=EXPRESS
      - SA_PASSWORD=z@123456!
    ports:
      - target: 1433
        published: 1434
  e-trans-vinhomes-api:
    container_name: e-trans-vinhomes-api
    tty: true
    image: ${DOCKER_REGISTRY-}e-trans-vinhomes-api:v1
    build:
      context: .
      dockerfile: ETransVinhomesAPI/Dockerfile
    environment:
    - CONNECTIONSTRINGS__DEFAULT=Server=sql-server;Database=ETransVinhomes;Trusted_Connection=False;User Id=sa;Password=z@123456!;MultipleActiveResultSets=true;TrustServerCertificate=true
    ports:
    - "4201:80"
  ocelot-api-gateway:
    container_name: ocelot-gateway
    image: ${DOCKER_REGISTRY-}ocelot-api-gateway:v1
    build: 
      context: .
      dockerfile: OcelotAPIGateway/Dockerfile
    ports:
     - "7061:80"

